### PR TITLE
 fix: obtain original signature

### PR DESCRIPTION
**Pull request by MALTF**
After authentication, the original signature can be read without any permission.

### CODE REVIEW

**Comment by xihan123** [comment]
为啥非要用一堆反射....

**Comment by MALTF** [comment]
因为经过项目认证，只有这个方式获取签名最靠谱
在HUAWEI LIO-AN00m Android 10, API 29上测试 signingInfo 一直都是 null 获取不到

**Comment by MALTF** [comment]
> 为啥非要用一堆反射....

[Check signature of an apk](https://stackoverflow.com/questions/62039401/check-signature-of-an-apk/69801172#69801172)
[PackageManager.getPackageArchiveInfo with GET_SIGNING_CERTIFICATES returning null signing info](https://stackoverflow.com/questions/71356010/packagemanager-getpackagearchiveinfo-with-get-signing-certificates-returning-nul)
[PackageManager#getPackageArchiveInfo() doesn't return signing info when passed PackageManager#GET_SIGNING_CERTIFICATES](https://issuetracker.google.com/issues/243324820)

**Comment by MALTF** [comment]
OnePlus  8 Pro Android 13 API 33 
[SignHook-release_2.0.3-T_191.apk](https://github.com/MALTF/SignHookDraft/releases/download/v2.0.3-T/SignHook-release_2.0.3-T_191.apk)

获取原始签名成功

**Comment by xihan123** [comment]
你试了2.0.2 能不能用吗

**Comment by MALTF** [comment]
> 你试了2.0.2 能不能用吗

signingInfo 一直都是 null 获取不到
你可以找个安卓 10 的设备试试

**Pull request closed without merging**
